%% Draw given robot configuration, including obstacles and desired
%% end-effector line.
%%
%% Arguments:
%%   q:  Joint variable array ([q1, q2, q3, q4]).
%%   ob: Obstacle array ([ob1_x, ob1_y, ob2_x, ob2_y]).
%%   dl: Desired end-effector line array ([a, b, c], where the
%%       desired line has equation ax + bx + c = 0).
function draw(q, ob, dl)
    clf('reset');
    hold on;
    plot(dl(1), 0, 's', 'MarkerSize', 25);
    axis([-5 5 -5 5]);
    %%axis equal;
    
% $$$     %% animation
% $$$ linecol = [0 0 0];
% $$$ jointcol = [0 0 0.5];
% $$$ edgecol = [0 0 0.5];
% $$$ if danim
% $$$   figure('OuterPosition', [200 100 800 800]);
% $$$ 
% $$$   dtk = 2;
% $$$   f = 1;
% $$$   for tk=1:dtk:length(t)
% $$$      clf('reset')
% $$$      hold on;
% $$$      
% $$$      plot(x, z, '.r', 'MarkerSize', 10); 
% $$$      line([0, 0], [0, l1 + q2(tk)],...
% $$$           'LineWidth', 8, 'Color', linecol);
% $$$      line([0, l2 + q3(tk)], [l1 + q2(tk), l1 + q2(tk)],...
% $$$           'LineWidth', 8, 'Color', linecol);
% $$$      line([l2 + q3(tk), l2 + q3(tk)], [l1 + q2(tk), l1 - l3 + q2(tk)],...
% $$$           'LineWidth', 8, 'Color', linecol);
% $$$      line([l2 + q3(tk), l2 + q3(tk) + l4 * cos(q4(tk))],...
% $$$           [l1 - l3 + q2(tk), l1 - l3 + q2(tk) - l4 * sin(q4(tk))],...
% $$$           'LineWidth', 5, 'Color', linecol);
% $$$      plot(0, l1 + q2(tk), 'o',...
% $$$           'MarkerSize', 7, 'MarkerFaceColor', linecol,...
% $$$           'MarkerEdgeColor', linecol);
% $$$      plot(l2 + q3(tk), l1 + q2(tk), 'o',...
% $$$           'MarkerSize', 7, 'MarkerFaceColor', linecol,...
% $$$           'MarkerEdgeColor', linecol);
% $$$ 
% $$$      plot(0, 5, 'o',...
% $$$           'MarkerSize', 20, 'MarkerFaceColor', jointcol,...
% $$$           'MarkerEdgeColor', edgecol);
% $$$      plot(0, 0, 's',...
% $$$           'MarkerSize', 25, 'MarkerFaceColor', jointcol,...
% $$$           'MarkerEdgeColor', edgecol);
% $$$           
% $$$      plot(0, l1-3, 's',...
% $$$           'MarkerSize', 20, 'MarkerFaceColor', jointcol,...
% $$$           'MarkerEdgeColor', edgecol);
% $$$      plot(0, l1, 's',...
% $$$           'MarkerSize', 20, 'MarkerFaceColor', jointcol,...
% $$$           'MarkerEdgeColor', edgecol);
% $$$           
% $$$      plot(l2-3, l1 + q2(tk), 's',...
% $$$           'MarkerSize', 20, 'MarkerFaceColor', jointcol,...
% $$$           'MarkerEdgeColor', edgecol);
% $$$      plot(l2, l1 + q2(tk), 's',...
% $$$           'MarkerSize', 20, 'MarkerFaceColor', jointcol,...
% $$$           'MarkerEdgeColor', edgecol);
% $$$           
% $$$      plot(l2 + q3(tk), l1 - l3 + q2(tk), 'o',...
% $$$           'MarkerSize', 15, 'MarkerFaceColor', jointcol,...
% $$$           'MarkerEdgeColor', edgecol);
% $$$           
% $$$      plot(l2 + q3(tk) + l4 * cos(q4(tk)),...
% $$$           l1 - l3 + q2(tk) - l4 * sin(q4(tk)), 'y.',...
% $$$           'MarkerSize', 20');
% $$$      plot(l2 + q3(tk) + l4 * cos(q4(tk)),...
% $$$           l1 - l3 + q2(tk) - l4 * sin(q4(tk)), 'y*',...
% $$$           'MarkerSize', 5');
% $$$ 
% $$$      axis([-50 150 -20 180])
% $$$      axis equal
% $$$ 
% $$$      M(f) = getframe;
% $$$      f = f + 1;
% $$$   end
% $$$   f = f - 1;
% $$$   
% $$$   movie(M, 10, f / T)
% $$$ end